// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package agent

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Response_Status int32

const (
	Response_SUCCESS Response_Status = 0
	Response_FAIL    Response_Status = 1
)

var Response_Status_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}
var Response_Status_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x Response_Status) String() string {
	return proto.EnumName(Response_Status_name, int32(x))
}
func (Response_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_agent_aee015f59c6e6f0b, []int{1, 0}
}

// The request message containing the user's name.
type Request struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId" json:"clientId,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_aee015f59c6e6f0b, []int{0}
}
func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (dst *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(dst, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Request) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

// The response message containing the greetings
type Response struct {
	Status               Response_Status `protobuf:"varint,1,opt,name=status,enum=agent.Response_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_agent_aee015f59c6e6f0b, []int{1}
}
func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (dst *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(dst, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetStatus() Response_Status {
	if m != nil {
		return m.Status
	}
	return Response_SUCCESS
}

func init() {
	proto.RegisterType((*Request)(nil), "agent.Request")
	proto.RegisterType((*Response)(nil), "agent.Response")
	proto.RegisterEnum("agent.Response_Status", Response_Status_name, Response_Status_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RemoteAgentClient is the client API for RemoteAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RemoteAgentClient interface {
	// Sends a greeting
	KickClient(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	PubMsg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type remoteAgentClient struct {
	cc *grpc.ClientConn
}

func NewRemoteAgentClient(cc *grpc.ClientConn) RemoteAgentClient {
	return &remoteAgentClient{cc}
}

func (c *remoteAgentClient) KickClient(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/agent.RemoteAgent/KickClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *remoteAgentClient) PubMsg(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/agent.RemoteAgent/PubMsg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RemoteAgentServer is the server API for RemoteAgent service.
type RemoteAgentServer interface {
	// Sends a greeting
	KickClient(context.Context, *Request) (*Response, error)
	PubMsg(context.Context, *Request) (*Response, error)
}

func RegisterRemoteAgentServer(s *grpc.Server, srv RemoteAgentServer) {
	s.RegisterService(&_RemoteAgent_serviceDesc, srv)
}

func _RemoteAgent_KickClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteAgentServer).KickClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.RemoteAgent/KickClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteAgentServer).KickClient(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _RemoteAgent_PubMsg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RemoteAgentServer).PubMsg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/agent.RemoteAgent/PubMsg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RemoteAgentServer).PubMsg(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _RemoteAgent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "agent.RemoteAgent",
	HandlerType: (*RemoteAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KickClient",
			Handler:    _RemoteAgent_KickClient_Handler,
		},
		{
			MethodName: "PubMsg",
			Handler:    _RemoteAgent_PubMsg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_agent_aee015f59c6e6f0b) }

var fileDescriptor_agent_aee015f59c6e6f0b = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x18, 0xc5, 0x17, 0xd1, 0xb6, 0x7e, 0x95, 0x59, 0x72, 0x90, 0xb2, 0x83, 0x8e, 0x9e, 0x06, 0x42,
	0x84, 0xe9, 0x5d, 0xb6, 0xa2, 0x30, 0x54, 0x28, 0x29, 0x9e, 0x3c, 0xb5, 0xd9, 0x47, 0x57, 0xea,
	0x92, 0xda, 0x7c, 0xc5, 0x7f, 0x5f, 0x96, 0xb9, 0x22, 0x9e, 0x76, 0x7c, 0xc9, 0xfb, 0xde, 0xfb,
	0xf1, 0x20, 0x2c, 0x2a, 0xd4, 0x24, 0xda, 0xce, 0x90, 0xe1, 0x67, 0x4e, 0x24, 0x8f, 0xe0, 0x4b,
	0xfc, 0xea, 0xd1, 0x12, 0x9f, 0x40, 0xa0, 0x3e, 0x6b, 0xd4, 0xb4, 0x5a, 0xc7, 0x6c, 0xca, 0x66,
	0xe7, 0x72, 0xd0, 0x3c, 0x06, 0x5f, 0x19, 0x4d, 0xa8, 0x29, 0x3e, 0x99, 0xb2, 0xd9, 0x85, 0x3c,
	0xc8, 0xe4, 0x03, 0x02, 0x89, 0xb6, 0x35, 0xda, 0x22, 0x17, 0xe0, 0x59, 0x2a, 0xa8, 0xb7, 0xee,
	0x7e, 0x3c, 0xbf, 0x12, 0xfb, 0xc6, 0x83, 0x41, 0xe4, 0xee, 0x57, 0xfe, 0xba, 0x92, 0x1b, 0xf0,
	0xf6, 0x2f, 0x3c, 0x04, 0x3f, 0x7f, 0x4f, 0xd3, 0xa7, 0x3c, 0x8f, 0x46, 0x3c, 0x80, 0xd3, 0xe7,
	0xc5, 0xea, 0x35, 0x62, 0xf3, 0x06, 0x42, 0x89, 0x5b, 0x43, 0xb8, 0xd8, 0xe5, 0xf0, 0x3b, 0x80,
	0x97, 0x5a, 0x35, 0xa9, 0xa3, 0xe2, 0xe3, 0x21, 0xdd, 0xf1, 0x4f, 0x2e, 0xff, 0xb5, 0x25, 0x23,
	0x7e, 0x0b, 0x5e, 0xd6, 0x97, 0x6f, 0xb6, 0x3a, 0xc2, 0xbc, 0x7c, 0x80, 0xeb, 0xaa, 0xa6, 0x4d,
	0x5f, 0x0a, 0x65, 0xb6, 0xc2, 0xaa, 0x4d, 0x69, 0x4c, 0x23, 0xbe, 0x6b, 0xbd, 0xc6, 0xa2, 0x13,
	0x5d, 0xab, 0x96, 0xd1, 0x1f, 0x98, 0x6c, 0xb7, 0x62, 0xc6, 0x4a, 0xcf, 0xcd, 0x79, 0xff, 0x13,
	0x00, 0x00, 0xff, 0xff, 0xec, 0x07, 0xe9, 0x01, 0x5d, 0x01, 0x00, 0x00,
}
